I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script_b_WeekLoop.rpy", line 207, in script
    
Exception: DynamicImage u'[R_img]': could not find image. (u'Schedule/R Study.png')

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script_b_WeekLoop.rpy", line 207, in script
    
  File "C:\Users\Benjamin Shu\Documents\renpy-6.99.14.1-sdk\renpy\ast.py", line 678, in execute
    renpy.exports.say(who, what, interact=self.interact, *args, **kwargs)
  File "C:\Users\Benjamin Shu\Documents\renpy-6.99.14.1-sdk\renpy\exports.py", line 1229, in say
    who(what, *args, **kwargs)
  File "C:\Users\Benjamin Shu\Documents\renpy-6.99.14.1-sdk\renpy\character.py", line 1031, in __call__
    self.do_display(who, what, cb_args=self.cb_args, **display_args)
  File "C:\Users\Benjamin Shu\Documents\renpy-6.99.14.1-sdk\renpy\character.py", line 823, in do_display
    **display_args)
  File "C:\Users\Benjamin Shu\Documents\renpy-6.99.14.1-sdk\renpy\character.py", line 572, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "C:\Users\Benjamin Shu\Documents\renpy-6.99.14.1-sdk\renpy\ui.py", line 289, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\Benjamin Shu\Documents\renpy-6.99.14.1-sdk\renpy\display\core.py", line 2672, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "C:\Users\Benjamin Shu\Documents\renpy-6.99.14.1-sdk\renpy\display\core.py", line 3059, in interact_core
    root_widget.visit_all(lambda i : i.per_interact())
  File "C:\Users\Benjamin Shu\Documents\renpy-6.99.14.1-sdk\renpy\display\core.py", line 531, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\Benjamin Shu\Documents\renpy-6.99.14.1-sdk\renpy\display\core.py", line 531, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\Benjamin Shu\Documents\renpy-6.99.14.1-sdk\renpy\display\core.py", line 531, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\Benjamin Shu\Documents\renpy-6.99.14.1-sdk\renpy\display\core.py", line 531, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\Benjamin Shu\Documents\renpy-6.99.14.1-sdk\renpy\display\core.py", line 531, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\Benjamin Shu\Documents\renpy-6.99.14.1-sdk\renpy\display\core.py", line 531, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\Benjamin Shu\Documents\renpy-6.99.14.1-sdk\renpy\display\core.py", line 531, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\Benjamin Shu\Documents\renpy-6.99.14.1-sdk\renpy\display\core.py", line 521, in visit_all
    for d in self.visit():
  File "C:\Users\Benjamin Shu\Documents\renpy-6.99.14.1-sdk\renpy\display\image.py", line 727, in visit
    self.find_target()
  File "C:\Users\Benjamin Shu\Documents\renpy-6.99.14.1-sdk\renpy\display\image.py", line 637, in find_target
    raise Exception(error)
Exception: DynamicImage u'[R_img]': could not find image. (u'Schedule/R Study.png')

Windows-8-6.2.9200
Ren'Py 7.1.3.1092
SBU Senior Project 1.0
Tue Feb 26 02:32:26 2019
