I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script_c_Week1.rpy", line 59, in script
    F "Hello!"
Exception: Sayer 'F' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script_c_Week1.rpy", line 59, in script
    F "Hello!"
  File "C:\Users\Benjamin Shu\Documents\renpy-6.99.14.1-sdk\renpy\ast.py", line 650, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Benjamin Shu\Documents\renpy-6.99.14.1-sdk\renpy\ast.py", line 560, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'F' is not defined.

Windows-8-6.2.9200
Ren'Py 7.1.3.1092
SBU Senior Project 1.0
Thu Feb 07 01:04:41 2019
